dataset_class: contrail_dataset
model_class: contrail_model 
exp_name: ../output/exp_03
# model_type: 'timm_unet'
debug: false
architecture:
    model_name: 'Unet'
    backbone: 'efficientnet-b7'
    pretrained: true
    mixout: 0.0
    default_weight: 'imagenet'
    pretrained_weights: ""
    pool: Mean 
dataset:
    fold: -1
    num_folds: 5
    num_classes: 1
    remove_outleirs: false
    train_df: "../input/train_data.csv"
    valid_df: "../input/valid_data.csv"
    train_path: "../input/train_data"
    valid_path: "../input/valid_data"
    folds_csv: ../input/folds_data.csv
    base_dir: ../input
    target_col: 'preds'
    num_folds: 5
    img_width: 256 #256 #256 #256
    img_height: 256 #256 #256 #256
environment:
    mixed_precision: true
    num_workers: 4
    seed: 42
training:
    use_pl: false
    ntb: 3
    replace_label: false
    loss: bce+mixed_loss # "bce+mixed_loss" # bce , bce+mixed_loss, bce+lovastz, bce+tversky, dice
    augs_train: "train_1"
    augs_val: "valid_2"
    fp16: true
    epochs: 200
    save_best: true
    batch_size: 112 #86
    grad_accumulation: 1
    batch_scheduler: true
    lr: 2.0e-3 #2.0e-3 #1.e-4 #2.0e-3
aux_params:
    pooling: 'avg'
    dropout: 0.5
    activation: 'sigmoid'
    classes: 1
wandb: 
    enable: false
    project_name: lrng_equality
awp:
    enable: false
    start_epoch: 2