dataset_class: contrail_dataset
model_class: contrail_model 
exp_name: ../output1/exp_10_s2
model_type: 'timm_unet'
debug: false
architecture:
    model_name: 'Unet'
    backbone: 'eca_nfnet_l0' # 'ecaresnet269d' #'eca_resnext26ts' #'cs3sedarknet_l' #cs3edgenet_x, 'cs3darknet_focus_l', 'cs3darknet_l'
    pretrained: true
    mixout: 0.0
    default_weight: 'imagenet'
    pretrained_weights: "/home/rohits/pv1/Contrail_Detection/output1/exp_10_01/Unet/eca_nfnet_l0-512"
    pool: Mean 
dataset:
    mixup: false
    cutmix: false
    fold: -1
    num_folds: 5
    num_classes: 1
    remove_outleirs: false
    train_df: "../input/train_data.csv"
    valid_df: "../input/valid_data.csv"
    train_path: "../input/train_data"
    valid_path: "../input/valid_data"
    folds_csv: ../input/folds_data.csv
    base_dir: ../input
    target_col: 'preds'
    num_folds: 5
    img_width: 512 #512 #256 #256 #256
    img_height: 512 #512 #256 #256 #256
environment:
    mixed_precision: true
    num_workers: 4
    seed: 42
training:
    use_pl: true
    pl_version: "v4"
    ntb: 3
    replace_label: false
    loss: dice # bce , bce+mixed_loss, bce+lovastz, bce+tversky, dice
    augs_train: "train_1"
    augs_val: "valid_2"
    fp16: true
    epochs: 15
    save_best: true
    batch_size: 42 #86
    grad_accumulation: 1
    batch_scheduler: true
    lr: 1.0e-4 #1.0e-3 #2.0e-3 #1.e-4 #2.0e-3
aux_params:
    pooling: 'avg'
    dropout: 0.5
    activation: 'sigmoid'
    classes: 1
wandb: 
    enable: false
    project_name: lrng_equality
awp:
    enable: false
    start_epoch: 2